-- * make an order for a book

CREATE OR REPLACE PROCEDURE ORDER_BOOK(
    V_USER_ID USERS.USER_ID%TYPE,
    V_BOOK_ID BOOKS.BOOK_ID%TYPE,
    RENTAL_PERIOD_MONTHS NUMBER
) AS
    INVALID_RENTAL_PERIOD EXCEPTION;
    PRAGMA EXCEPTION_INIT(INVALID_RENTAL_PERIOD, -20001);
BEGIN
 -- check if months number >= 0
    IF RENTAL_PERIOD_MONTHS <= 0 THEN
        RAISE INVALID_RENTAL_PERIOD;
    END IF;
 -- check if book_id exists
    IF NOT VALIDATE_DATA.CHECK_BOOK_EXISTS(V_BOOK_ID) THEN
        RAISE VALIDATE_DATA.INVALID_BOOK_ID;
    END IF;
 -- check if user_id exists
    IF NOT VALIDATE_DATA.CHECK_USER_EXISTS(V_USER_ID) THEN
        RAISE VALIDATE_DATA.INVALID_USER_ID;
    END IF;
    INSERT INTO ORDERED (
        BOOKS_BOOK_ID,
        USERS_USER_ID,
        TIME
    ) VALUES(
        V_BOOK_ID,
        V_USER_ID,
        RENTAL_PERIOD_MONTHS
    );
END ORDER_BOOK;
