-- check if book exists -> delete from borrowed
CREATE OR REPLACE PROCEDURE RETURN_BOOK(
    V_USER_ID USERS.USER_ID%TYPE,
    V_BOOK_ID BOOKS.BOOK_ID%TYPE
) AS
BEGIN
 -- check if book exists in db m
    IF NOT VALIDATE_DATA.CHECK_BOOK_EXISTS(V_BOOK_ID) THEN
        RAISE VALIDATE_DATA.INVALID_BOOK_ID;
    END IF;
 -- check if user exists
    IF NOT VALIDATE_DATA.CHECK_USER_EXISTS(V_USER_ID) THEN
        RAISE VALIDATE_DATA.INVALID_USER_ID;
    END IF;
    DELETE FROM BORROWED
    WHERE
        BOOK_ID = V_BOOK_ID
        AND USER_ID = V_USER_ID;
END RETURN_BOOK;
