CREATE TABLE books (
    book_id       NUMBER (4) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 2000,
    name          VARCHAR2(40 CHAR) NOT NULL,
    author        VARCHAR2(40 CHAR) NOT NULL,
    category      VARCHAR2(40 CHAR),
    department_id INTEGER NOT NULL
);
ALTER TABLE books ADD CONSTRAINT books_pk PRIMARY KEY ( book_id );

CREATE TABLE borrowed (
    borrow_id   NUMBER (4) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 100,
    user_id     INTEGER NOT NULL,
    book_id     INTEGER NOT NULL,
    return_date DATE NOT NULL,
    borrow_date DATE NOT NULL
);

ALTER TABLE borrowed ADD CONSTRAINT borrowed_pk PRIMARY KEY ( borrow_id );

CREATE TABLE departments (
    department_id NUMBER (4) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 2000,
    name          VARCHAR2(40 CHAR) NOT NULL,
    city          VARCHAR2(40 CHAR) NOT NULL,
    manager_id    INTEGER NOT NULL
);

ALTER TABLE departments ADD CONSTRAINT departments_pk PRIMARY KEY ( department_id );

CREATE TABLE employee_id_to_login (
    login       VARCHAR2(20 CHAR) NOT NULL,
    employee_id INTEGER NOT NULL
);

ALTER TABLE employee_id_to_login ADD CONSTRAINT employee_id_to_login_pk PRIMARY KEY ( employee_id );

CREATE TABLE employee_login (
    login    VARCHAR2(20 CHAR) NOT NULL,
    password VARCHAR2(20 CHAR) NOT NULL
);

ALTER TABLE employee_login ADD CONSTRAINT employee_login_pk PRIMARY KEY ( login );

CREATE TABLE employees (
    employee_id   NUMBER (4) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 2000,
    name          VARCHAR2(40 CHAR) NOT NULL,
    surname       VARCHAR2(40 BYTE) NOT NULL,
    email         VARCHAR2(60 CHAR) NOT NULL,
    phone_number  VARCHAR2(20 CHAR) NOT NULL,
    department_id INTEGER NOT NULL
);

ALTER TABLE employees ADD CONSTRAINT employees_pk PRIMARY KEY ( employee_id );

CREATE TABLE manager_id_to_login (
    manager_id INTEGER NOT NULL,
    login      VARCHAR2(20 CHAR) NOT NULL
);

ALTER TABLE manager_id_to_login ADD CONSTRAINT manager_id_to_login_pk PRIMARY KEY ( manager_id );

CREATE TABLE managers (
    manager_id NUMBER (4) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 2000,
    name       VARCHAR2(40 CHAR) NOT NULL,
    surname    VARCHAR2(40 BYTE) NOT NULL
);

ALTER TABLE managers ADD CONSTRAINT managers_pk PRIMARY KEY ( manager_id );

CREATE TABLE managers_login (
    login    VARCHAR2(20 CHAR) NOT NULL,
    password VARCHAR2(20 CHAR) NOT NULL
);

ALTER TABLE managers_login ADD CONSTRAINT managers_login_pk PRIMARY KEY ( login );

CREATE TABLE ordered (
    order_id      NUMBER (4) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 100,
    books_book_id INTEGER NOT NULL,
    users_user_id INTEGER NOT NULL,
    time          INTEGER NOT NULL
);

ALTER TABLE ordered ADD CONSTRAINT ordered_pk PRIMARY KEY ( order_id );

CREATE TABLE user_id_to_login (
    user_id INTEGER NOT NULL,
    login   VARCHAR2(20 CHAR) NOT NULL
);

ALTER TABLE user_id_to_login ADD CONSTRAINT user_id_to_login_pk PRIMARY KEY ( user_id );

CREATE TABLE users (
    user_id      NUMBER (4) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 2000,
    name         VARCHAR2(40 CHAR) NOT NULL,
    surname      VARCHAR2(40 BYTE) NOT NULL,
    email        VARCHAR2(60 CHAR) NOT NULL,
    phone_number VARCHAR2(20 CHAR)
);

ALTER TABLE users ADD CONSTRAINT users_pk PRIMARY KEY ( user_id );

CREATE TABLE users_login (
    login    VARCHAR2(20 CHAR) NOT NULL,
    password VARCHAR2(20 CHAR) NOT NULL
);

ALTER TABLE users_login ADD CONSTRAINT users_login_pk PRIMARY KEY ( login );

ALTER TABLE books
    ADD CONSTRAINT books_departments_fk FOREIGN KEY ( department_id )
        REFERENCES departments ( department_id );

ALTER TABLE borrowed
    ADD CONSTRAINT borrowed_books_fk FOREIGN KEY ( book_id )
        REFERENCES books ( book_id );

ALTER TABLE borrowed
    ADD CONSTRAINT borrowed_users_fk FOREIGN KEY ( user_id )
        REFERENCES users ( user_id );

ALTER TABLE departments
    ADD CONSTRAINT departments_managers_fk FOREIGN KEY ( manager_id )
        REFERENCES managers ( manager_id );

ALTER TABLE employee_id_to_login
    ADD CONSTRAINT emp_idtolog_id_fk FOREIGN KEY ( employee_id )
        REFERENCES employees ( employee_id );

ALTER TABLE employee_id_to_login
    ADD CONSTRAINT emp_idtolog_login_fk FOREIGN KEY ( login )
        REFERENCES employee_login ( login );

ALTER TABLE employees
    ADD CONSTRAINT employees_dep_id_fk FOREIGN KEY ( department_id )
        REFERENCES departments ( department_id );

ALTER TABLE manager_id_to_login
    ADD CONSTRAINT man_idtolog_id_fk FOREIGN KEY ( manager_id )
        REFERENCES managers ( manager_id );

ALTER TABLE manager_id_to_login
    ADD CONSTRAINT man_idtolog_login_fk FOREIGN KEY ( login )
        REFERENCES managers_login ( login );

ALTER TABLE ordered
    ADD CONSTRAINT ordered_books_fk FOREIGN KEY ( books_book_id )
        REFERENCES books ( book_id );

ALTER TABLE ordered
    ADD CONSTRAINT ordered_users_fk FOREIGN KEY ( users_user_id )
        REFERENCES users ( user_id );

ALTER TABLE user_id_to_login
    ADD CONSTRAINT user_idtolog_id_fk FOREIGN KEY ( user_id )
        REFERENCES users ( user_id );

ALTER TABLE user_id_to_login
    ADD CONSTRAINT user_idtolog_log_fk FOREIGN KEY ( login )
        REFERENCES users_login ( login );

commit;
